// Initiates database object
                const users = {
                                admin: {password: "admin", status: "Apapo Odu Cultural Organization" },
                                adedeji: {password: "mother", status: "Osa Owonrin, Ire Aiku, Adimu Eegun"},
                                initiateName1: {password: "mother", status: "Ejiogbe , Ire Aje, Adimu Eegun"},
                                initiateName2: {password: "mother", status: "Oyeku Meji, , Ire Isegun, Adimu Eegun"},
                                initiateName3: {password: "mother", status: "Iwori Meji, Ire Igbalese, Adimu Eegun"},
                                initiateName4: {password: "mother", status: "Idi Meji, Gbogbo Ire, Adimu Eegun"},
                                initiateName5: {password: "mother", status: "Irosun Meji, Ayewo Iku, Adimu Eegun"},
                                initiateName6: {password: "mother", status: "Owonrin Meji, Ayewo Arun, Adimu Eegun"},
                                initiateName7: {password: "mother", status: "Obara Meji, Ayewo Ejo, Adimu Eegun"},
                                initiateName8: {password: "mother", status: "Okanran Meji, Ayewo Ofo, Adimu Eegun"},
                                initiateName9: {password: "mother", status: "Ogunda Meji, Ayewo Okutagbunilese, Adimu Eegun"},
                                initiateName10: {password: "mother", status: "Osa Meji, Ire Aiku, Adimu Osha"},
                                initiateName11: {password: "mother", status: "Ika Meji, Ire Aiku, Adimu Ifa"},
                                initiateName12: {password: "mother", status: "Oturupon Meji, Ire Aiku, Adimu Ori"},
                                initiateName13: {password: "mother", status: "Otura Meji, Ire Aje, Ebo Akoru"},
                                initiateName14: {password: "mother", status: "Irete Meji, Ire Aiku, Ebo Esa"},
                                initiateName15: {password: "mother", status: "Ose Meji, Ire Isegun, Ebo Akoru"},
                                initiateName16: {password: "mother", status: "Ofun Meji, Ire Aiku, Adimu Ifa"},
                            };
